name: SuperDemucs
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - numpy=1.19.5
  - pandas
  - scipy>=1.8.0
  - librosa
  - tensorflow
  - tensorboard
  - jupyter
  - protobuf=3.20.3
  - pyrootutils
  - hydra-core==1.1.0
  - pydub
  - pip
  - ffmpeg
  - pip:
    - torch==2.0.1
    - segmentation_models_pytorch==0.3.3
    - timm==0.9.2
    - audiomentations==0.24.0
    - pedalboard==0.8.1
    - omegaconf==2.2.3
    - beartype==0.14.1
    - rotary_embedding_torch==0.3.5
    - einops==0.6.1
    - demucs==4.0.0
    - transformers==4.35.0
    - torchmetrics==0.11.4
    - spafe==0.3.2
    - torch_audiomentations
    - asteroid==0.7.0
    - auraloss
    - torchseg
    - soundfile
    - ml_collections==0.1.1
